In [9]:
import pandas as pd

data1 = {"Emp ID" : ["E01", "E02", "E03", "E04", "E05", "E06"],
         "Names" : ["Ram", "Shyam", "Rahul", "Vishal", "Ravi", "John"],
         "Age" : [34, 56, 43, 23, 45, 22]}
 
data2 = {"Emp ID" : ["E01", "E07", "E03", "E04", "E08", "E06"],
         "Salary" : [45000, 40000, 60000, 75000, 50000, 100000]}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

display(df1)
display(df2)

  Emp ID   Names  Age
0    E01     Ram   34
1    E02   Shyam   56
2    E03   Rahul   43
3    E04  Vishal   23
4    E05    Ravi   45
5    E06    John   22

  Emp ID  Salary
0    E01   45000
1    E07   40000
2    E03   60000
3    E04   75000
4    E08   50000
5    E06  100000

In [17]:
display(pd.merge(left = df1, right = df2, on = "Emp ID", how = "left"))

  Emp ID   Names  Age    Salary
0    E01     Ram   34   45000.0
1    E02   Shyam   56       NaN
2    E03   Rahul   43   60000.0
3    E04  Vishal   23   75000.0
4    E05    Ravi   45       NaN
5    E06    John   22  100000.0

In [1]:
import pandas as pd

data1 = {"Emp ID" : ["E01", "E02", "E03", "E04", "E05", "E06"],
         "Names" : ["Ram", "Shyam", "Rahul", "Vishal", "Ravi", "John"],
         "Age" : [34, 56, 43, 23, 45, 22]}

data2 = {"Emp ID" : ["E07", "E08", "E09", "E10", "E11", "E12"],
         "Names" : ["shaur", "rudra", "prayank", "arnav", "krish", "bhaskar"],
         "Age" : [34, 56, 43, 23, 48, 23]}


df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [5]:
display((pd.concat([df1,df2])))

  Emp ID    Names  Age
0    E01      Ram   34
1    E02    Shyam   56
2    E03    Rahul   43
3    E04   Vishal   23
4    E05     Ravi   45
5    E06     John   22
0    E07    shaur   34
1    E08    rudra   56
2    E09  prayank   43
3    E10    arnav   23
4    E11    krish   48
5    E12  bhaskar   23