In [7]:
import pandas as pd

data = pd.read_csv("small_sample.csv")
display(data)

data["Marks Deducted"] = (100 - data["Marks"])
display(data)

   ID     Name  Age            Course  Marks
0   1  Shaurya   19            Python     88
1   2     Alex   20    Data Analytics     92
2   3     Riya   18  Machine Learning     85
3   4    Kabir   21        Statistics     79
4   5   Ananya   20               SQL     95

   ID     Name  Age            Course  Marks  Marks Deducted
0   1  Shaurya   19            Python     88              12
1   2     Alex   20    Data Analytics     92               8
2   3     Riya   18  Machine Learning     85              15
3   4    Kabir   21        Statistics     79              21
4   5   Ananya   20               SQL     95               5

In [14]:
data = {"Months" : ["January", "February", "March", "April"]}

a = pd.DataFrame(data)
print(a)

def extract(value):
    return value[0:3]

a["Short Months"] = a["Months"].map(extract)        #method to create a new column using an existing column
print(a)

     Months
0   January
1  February
2     March
3     April
     Months Short Months
0   January          Jan
1  February          Feb
2     March          Mar
3     April          Apr