In [25]:
import pandas as pd

df = pd.read_excel("ESP.xlsx")
#display(df)

df.loc[(df["Bonus %"] < 9), "Get Bonus"] = "less bonus"
df.loc[(df["Bonus %"] >= 9), "Get Bonus"] = "bonus"
display(df.head(5))

,EEID,Full Name,Job Title,Department,Bonus %,City,Country,Exit Date,Get Bonus
0,EMP001,Alex Patel,Marketing Specialist,HR,13.09,Jaipur,USA,2023-09-03,bonus
1,EMP002,Dev Mehta,Sales Executive,Finance,20.91,Ahmedabad,Germany,NaN,bonus
2,EMP003,Yash Nair,Product Manager,HR,10.72,Bangalore,India,NaN,bonus
3,EMP004,Shaurya Kapoor,Business Analyst,Product,8.22,Chennai,Canada,2025-09-18,less bonus
4,EMP005,Neha Patel,Marketing Specialist,Finance,11.83,Noida,USA,NaN,bonus

In [32]:
import pandas as pd

data = pd.read_csv("small_sample.csv")
display(data)

# if we want Name and Course in the same column
data["Name & Course"] = data["Name"] + " is learning " + data["Course"]
display(data)

   ID     Name  Age            Course  Marks
0   1  Shaurya   19            Python     88
1   2     Alex   20    Data Analytics     92
2   3     Riya   18  Machine Learning     85
3   4    Kabir   21        Statistics     79
4   5   Ananya   20               SQL     95

,ID,Name,Age,Course,Marks,Name & Course
0,1,Shaurya,19,Python,88,Shaurya is learning Python
1,2,Alex,20,Data Analytics,92,Alex is learning Data Analytics
2,3,Riya,18,Machine Learning,85,Riya is learning Machine Learning
3,4,Kabir,21,Statistics,79,Kabir is learning Statistics
4,5,Ananya,20,SQL,95,Ananya is learning SQL