In [13]:
import pandas as pd

data = pd.read_excel("sample_learning_data.xlsx")
display(data)

   ID     Name  Age            Course  Marks
0   1  Shaurya   19            Python     88
1   2     Alex   20    Data Analytics     92
2   3     Riya   18  Machine Learning     85
3   4    Kabir   21        Statistics     79
4   5   Ananya   20               SQL     95

In [19]:
display(data["Age"].duplicated())
(data["Age"].duplicated().sum())       #tells us how many duplicates are there in total

0    False
1    False
2    False
3    False
4     True
Name: Age, dtype: bool

np.int64(1)

In [ ]:
data.drop_duplicates("Age")     #dropped the duplicate BUT only use this when we check something like ID which has to be unique (Primary key)

   ID     Name  Age            Course  Marks
0   1  Shaurya   19            Python     88
1   2     Alex   20    Data Analytics     92
2   3     Riya   18  Machine Learning     85
3   4    Kabir   21        Statistics     79