In [9]:
import pandas as pd

data = pd.read_csv("null.csv")
display(data)

    ID     Name   Age          Course  Marks    City  Attendance
0    1  Shaurya  19.0          Python   90.0  Mumbai        80.0
1    2     Alex   NaN              ML   72.0  Jaipur        90.0
2    3      NaN  19.0              ML   80.0     NaN        90.0
3    4   Ananya  22.0             SQL   80.0   Delhi        70.0
4    5     Riya  19.0          Python   72.0     NaN         NaN
5    6   Ananya  21.0  Data Analytics   65.0     NaN         NaN
6    7     Alex  20.0  Data Analytics   65.0     NaN        70.0
7    8      NaN  18.0          Python   90.0   Delhi        70.0
8    9     Alex  18.0             NaN   65.0  Mumbai       100.0
9   10     Alex  20.0              ML   80.0   Delhi        80.0
10  11  Shaurya  21.0          Python   72.0  Mumbai        90.0
11  12   Ananya   NaN             SQL   80.0     NaN        80.0
12  13   Ananya  19.0             NaN   65.0     NaN        80.0
13  14      NaN  19.0          Python    NaN  Mumbai         NaN
14  15   Ananya  21.0             NaN    NaN  Mumbai         NaN
15  16     Riya  22.0          Python    NaN  Jaipur         NaN
16  17  Shaurya  18.0  Data Analytics   72.0   Delhi        80.0
17  18      NaN  18.0              ML    NaN   Delhi        70.0
18  19  Shaurya  22.0  Data Analytics   65.0  Mumbai        70.0
19  20    Kabir  20.0             NaN   65.0     NaN        80.0
20  21    Kabir  19.0          Python   80.0     NaN        70.0
21  22    Kabir  19.0  Data Analytics   72.0     NaN        70.0
22  23   Ananya  19.0             SQL   72.0  Mumbai         NaN
23  24     Alex  21.0              ML   72.0  Mumbai       100.0
24  25      NaN   NaN          Python    NaN  Mumbai       100.0
25  26    Kabir   NaN              ML   65.0   Delhi         NaN
26  27     Riya  18.0  Data Analytics   65.0   Delhi        70.0
27  28   Ananya   NaN          Python   72.0   Delhi        90.0
28  29  Shaurya  21.0             SQL   72.0   Delhi        70.0
29  30     Riya  20.0              ML   72.0   Delhi         NaN

In [10]:
data.isnull().sum()

ID            0
Name          5
Age           5
Course        4
Marks         5
City          9
Attendance    8
dtype: int64

In [14]:
display(data.dropna())

    ID     Name   Age          Course  Marks    City  Attendance
0    1  Shaurya  19.0          Python   90.0  Mumbai        80.0
3    4   Ananya  22.0             SQL   80.0   Delhi        70.0
9   10     Alex  20.0              ML   80.0   Delhi        80.0
10  11  Shaurya  21.0          Python   72.0  Mumbai        90.0
16  17  Shaurya  18.0  Data Analytics   72.0   Delhi        80.0
18  19  Shaurya  22.0  Data Analytics   65.0  Mumbai        70.0
23  24     Alex  21.0              ML   72.0  Mumbai       100.0
26  27     Riya  18.0  Data Analytics   65.0   Delhi        70.0
28  29  Shaurya  21.0             SQL   72.0   Delhi        70.0

In [ ]:
import numpy as np
display(data.replace(np.nan, "hi"))     # replaces null values with hi, but we don't want hi in attendance or anything else

    ID     Name   Age          Course Marks    City Attendance
0    1  Shaurya  19.0          Python  90.0  Mumbai       80.0
1    2     Alex    hi              ML  72.0  Jaipur       90.0
2    3       hi  19.0              ML  80.0      hi       90.0
3    4   Ananya  22.0             SQL  80.0   Delhi       70.0
4    5     Riya  19.0          Python  72.0      hi         hi
5    6   Ananya  21.0  Data Analytics  65.0      hi         hi
6    7     Alex  20.0  Data Analytics  65.0      hi       70.0
7    8       hi  18.0          Python  90.0   Delhi       70.0
8    9     Alex  18.0              hi  65.0  Mumbai      100.0
9   10     Alex  20.0              ML  80.0   Delhi       80.0
10  11  Shaurya  21.0          Python  72.0  Mumbai       90.0
11  12   Ananya    hi             SQL  80.0      hi       80.0
12  13   Ananya  19.0              hi  65.0      hi       80.0
13  14       hi  19.0          Python    hi  Mumbai         hi
14  15   Ananya  21.0              hi    hi  Mumbai         hi
15  16     Riya  22.0          Python    hi  Jaipur         hi
16  17  Shaurya  18.0  Data Analytics  72.0   Delhi       80.0
17  18       hi  18.0              ML    hi   Delhi       70.0
18  19  Shaurya  22.0  Data Analytics  65.0  Mumbai       70.0
19  20    Kabir  20.0              hi  65.0      hi       80.0
20  21    Kabir  19.0          Python  80.0      hi       70.0
21  22    Kabir  19.0  Data Analytics  72.0      hi       70.0
22  23   Ananya  19.0             SQL  72.0  Mumbai         hi
23  24     Alex  21.0              ML  72.0  Mumbai      100.0
24  25       hi    hi          Python    hi  Mumbai      100.0
25  26    Kabir    hi              ML  65.0   Delhi         hi
26  27     Riya  18.0  Data Analytics  65.0   Delhi       70.0
27  28   Ananya    hi          Python  72.0   Delhi       90.0
28  29  Shaurya  21.0             SQL  72.0   Delhi       70.0
29  30     Riya  20.0              ML  72.0   Delhi         hi

In [17]:
data["City"] = data["City"].replace(np.nan, "Chennai")
display(data)

    ID     Name   Age          Course  Marks     City  Attendance
0    1  Shaurya  19.0          Python   90.0   Mumbai        80.0
1    2     Alex   NaN              ML   72.0   Jaipur        90.0
2    3      NaN  19.0              ML   80.0  Chennai        90.0
3    4   Ananya  22.0             SQL   80.0    Delhi        70.0
4    5     Riya  19.0          Python   72.0  Chennai         NaN
5    6   Ananya  21.0  Data Analytics   65.0  Chennai         NaN
6    7     Alex  20.0  Data Analytics   65.0  Chennai        70.0
7    8      NaN  18.0          Python   90.0    Delhi        70.0
8    9     Alex  18.0             NaN   65.0   Mumbai       100.0
9   10     Alex  20.0              ML   80.0    Delhi        80.0
10  11  Shaurya  21.0          Python   72.0   Mumbai        90.0
11  12   Ananya   NaN             SQL   80.0  Chennai        80.0
12  13   Ananya  19.0             NaN   65.0  Chennai        80.0
13  14      NaN  19.0          Python    NaN   Mumbai         NaN
14  15   Ananya  21.0             NaN    NaN   Mumbai         NaN
15  16     Riya  22.0          Python    NaN   Jaipur         NaN
16  17  Shaurya  18.0  Data Analytics   72.0    Delhi        80.0
17  18      NaN  18.0              ML    NaN    Delhi        70.0
18  19  Shaurya  22.0  Data Analytics   65.0   Mumbai        70.0
19  20    Kabir  20.0             NaN   65.0  Chennai        80.0
20  21    Kabir  19.0          Python   80.0  Chennai        70.0
21  22    Kabir  19.0  Data Analytics   72.0  Chennai        70.0
22  23   Ananya  19.0             SQL   72.0   Mumbai         NaN
23  24     Alex  21.0              ML   72.0   Mumbai       100.0
24  25      NaN   NaN          Python    NaN   Mumbai       100.0
25  26    Kabir   NaN              ML   65.0    Delhi         NaN
26  27     Riya  18.0  Data Analytics   65.0    Delhi        70.0
27  28   Ananya   NaN          Python   72.0    Delhi        90.0
28  29  Shaurya  21.0             SQL   72.0    Delhi        70.0
29  30     Riya  20.0              ML   72.0    Delhi         NaN

In [20]:
display(data.fillna(method = "bfill"))      # backward fill : the value is backwarded to the null value

/var/folders/hc/0hj953jj47b5k0cwy0lp1vqr0000gn/T/ipykernel_83384/375520685.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  display(data.fillna(method = "bfill"))      # backward fill : the value is backwarded to the null value

    ID     Name   Age          Course  Marks     City  Attendance
0    1  Shaurya  19.0          Python   90.0   Mumbai        80.0
1    2     Alex  19.0              ML   72.0   Jaipur        90.0
2    3   Ananya  19.0              ML   80.0  Chennai        90.0
3    4   Ananya  22.0             SQL   80.0    Delhi        70.0
4    5     Riya  19.0          Python   72.0  Chennai        70.0
5    6   Ananya  21.0  Data Analytics   65.0  Chennai        70.0
6    7     Alex  20.0  Data Analytics   65.0  Chennai        70.0
7    8     Alex  18.0          Python   90.0    Delhi        70.0
8    9     Alex  18.0              ML   65.0   Mumbai       100.0
9   10     Alex  20.0              ML   80.0    Delhi        80.0
10  11  Shaurya  21.0          Python   72.0   Mumbai        90.0
11  12   Ananya  19.0             SQL   80.0  Chennai        80.0
12  13   Ananya  19.0          Python   65.0  Chennai        80.0
13  14   Ananya  19.0          Python   72.0   Mumbai        80.0
14  15   Ananya  21.0          Python   72.0   Mumbai        80.0
15  16     Riya  22.0          Python   72.0   Jaipur        80.0
16  17  Shaurya  18.0  Data Analytics   72.0    Delhi        80.0
17  18  Shaurya  18.0              ML   65.0    Delhi        70.0
18  19  Shaurya  22.0  Data Analytics   65.0   Mumbai        70.0
19  20    Kabir  20.0          Python   65.0  Chennai        80.0
20  21    Kabir  19.0          Python   80.0  Chennai        70.0
21  22    Kabir  19.0  Data Analytics   72.0  Chennai        70.0
22  23   Ananya  19.0             SQL   72.0   Mumbai       100.0
23  24     Alex  21.0              ML   72.0   Mumbai       100.0
24  25    Kabir  18.0          Python   65.0   Mumbai       100.0
25  26    Kabir  18.0              ML   65.0    Delhi        70.0
26  27     Riya  18.0  Data Analytics   65.0    Delhi        70.0
27  28   Ananya  21.0          Python   72.0    Delhi        90.0
28  29  Shaurya  21.0             SQL   72.0    Delhi        70.0
29  30     Riya  20.0              ML   72.0    Delhi         NaN

In [21]:
display(data.fillna(method = "ffill"))      #forward fill : the value gets forwarded to the null value

/var/folders/hc/0hj953jj47b5k0cwy0lp1vqr0000gn/T/ipykernel_83384/4217981365.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  display(data.fillna(method = "ffill"))      #forward fill : the value gets forwarded to the null value

    ID     Name   Age          Course  Marks     City  Attendance
0    1  Shaurya  19.0          Python   90.0   Mumbai        80.0
1    2     Alex  19.0              ML   72.0   Jaipur        90.0
2    3     Alex  19.0              ML   80.0  Chennai        90.0
3    4   Ananya  22.0             SQL   80.0    Delhi        70.0
4    5     Riya  19.0          Python   72.0  Chennai        70.0
5    6   Ananya  21.0  Data Analytics   65.0  Chennai        70.0
6    7     Alex  20.0  Data Analytics   65.0  Chennai        70.0
7    8     Alex  18.0          Python   90.0    Delhi        70.0
8    9     Alex  18.0          Python   65.0   Mumbai       100.0
9   10     Alex  20.0              ML   80.0    Delhi        80.0
10  11  Shaurya  21.0          Python   72.0   Mumbai        90.0
11  12   Ananya  21.0             SQL   80.0  Chennai        80.0
12  13   Ananya  19.0             SQL   65.0  Chennai        80.0
13  14   Ananya  19.0          Python   65.0   Mumbai        80.0
14  15   Ananya  21.0          Python   65.0   Mumbai        80.0
15  16     Riya  22.0          Python   65.0   Jaipur        80.0
16  17  Shaurya  18.0  Data Analytics   72.0    Delhi        80.0
17  18  Shaurya  18.0              ML   72.0    Delhi        70.0
18  19  Shaurya  22.0  Data Analytics   65.0   Mumbai        70.0
19  20    Kabir  20.0  Data Analytics   65.0  Chennai        80.0
20  21    Kabir  19.0          Python   80.0  Chennai        70.0
21  22    Kabir  19.0  Data Analytics   72.0  Chennai        70.0
22  23   Ananya  19.0             SQL   72.0   Mumbai        70.0
23  24     Alex  21.0              ML   72.0   Mumbai       100.0
24  25     Alex  21.0          Python   72.0   Mumbai       100.0
25  26    Kabir  21.0              ML   65.0    Delhi       100.0
26  27     Riya  18.0  Data Analytics   65.0    Delhi        70.0
27  28   Ananya  18.0          Python   72.0    Delhi        90.0
28  29  Shaurya  21.0             SQL   72.0    Delhi        70.0
29  30     Riya  20.0              ML   72.0    Delhi        70.0